[project]
name = "fogies"
# Version follows semantic versioning <https://semver.org/>.
version = "0.0.0-dev.1"
description = ""
authors = [
    {name = "James Fogarty",email = "jayfo@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14"

[tool.poetry]
packages = [{include = "fogies", from = "src"}]

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]
black = ">=24.0.0"
invoke = ">=2.0.0"
isort = ">=5.13.0"
pytest = ">=8.0.0"
semver = ">=3.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

